---
title: "gfsynopsis-noaa"
format:
  dashboard: 
    orientation: rows
    #scrolling: true
    nav-buttons: 
      -icon: github
      href: https://github.com/DFO-NOAA-Pacific/gfsynopsis-noaa/tree/main
---

```{r, echo = FALSE}
library(tidyverse)
library(gt)
library(gtsummary)
library(glue)
library(gfsynopsisnoaa)
firstup <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
}

sp <- "arrowtooth flounder"

```

# {.sidebar}

Shiny can be used to create drop downs to select columns within your data.

# `r firstup(sp)`

## columns 

```{r}
#| echo: false
#| scrolling: true
#| title: Design-based biomass
plot_design_based(
  data = biomass[biomass$common_name == sp, ],
  plot = 1
)
```


```{r}
#| echo: false
#| scrolling: true
#| title: Design-based biomass
plot_design_based(
  data = biomass[biomass$common_name == sp, ],
  plot = 2
)
```


## columns

```{r}
#| echo: false
#| title: "Estimated length-mass relationship by region."
plot_biology(
  data = specimens[specimens$common_name == sp, ],
  parameters = parameters,
  plot = 1
)
```

```{r}
#| echo: false
#| title: "Estimated age-length relationship by region."
plot_biology(
  data = specimens[specimens$common_name == sp, ],
  parameters = parameters,
  plot = 2
)
```

## columns

```{r}
#| echo: false
#| message: false
#| label: samples-afsc
region_table <- "U.S. Gulf of Alaska"
samples |> 
  dplyr::filter(
    common_name == sp,
    region == region_table) |>
  dplyr::select(-common_name, -region) |>
  dplyr::rename(
    Year = year,
    Length = length,
    Age = age,
    Mass = mass
  ) |>
  gt::gt() |>
  gt::tab_header(
    title = glue::glue("Biological samples by year collected in {region_table}")
  ) |>
  gt::fmt_number(
    columns = 2:4,
    decimals = 0, 
    sep_mark = ","
  )
   
```

```{r}
#| echo: false
#| message: false
#| label: samples-nwfsc
region_table <- "U.S. West Coast"
samples |> 
  dplyr::filter(
    common_name == sp,
    region == region_table) |>
  dplyr::select(-common_name, -region) |>
  dplyr::rename(
    Year = year,
    Length = length,
    Age = age,
    Mass = mass
  ) |>
  gt::gt() |>
  gt::tab_header(
    title = glue::glue("Biological samples by year collected in {region_table}")
  ) |>
  gt::fmt_number(
    columns = 2:4,
    decimals = 0, 
    sep_mark = ","
  )
   
```
