---
title: "gfsynopsis-noaa"
format: 
  html
params:
  common_name: "Pacific ocean perch"
---

```{r}
#| label: load-data
#| echo: false
#| message: false
suppressMessages(library(tidyverse))
library(gt)
library(gtsummary)
library(glue)
library(gfsynopsisnoaa)

source(here::here("doc", "to_plot.R"))

```

```{r}
#| echo: false
#| message: false
#| label: section-name
firstup <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
  }
section_name <- firstup(params$common_name)
glue::glue(" \n{section_name} \n \n") |> cat( )
```


```{r}
#| echo: false
#| message: false
#| label: biomass
filtered_biomass <- biomass |> dplyr::filter(common_name == params$common_name)
bio_plot <- plot_design_based(
    data = filtered_biomass,
    plot = 1)
suppressWarnings(print(bio_plot))

```

```{r}
#| echo: false
#| message: false
#| label: biology
filtered_specimens <- specimens |> dplyr::filter(common_name == params$common_name)
mass_length <- plot_biology(
  data = filtered_specimens,
  parameters = parameters,
  plot = 1)

length_age <- plot_biology(
  data = filtered_specimens,
  parameters = parameters,
  plot = 2)

suppressWarnings(print(mass_length))
suppressWarnings(print(length_age))

```


```{r}
#| echo: false
#| message: false
#| label: samples
samples |> 
  dplyr::filter(common_name == params$common_name) |>
  dplyr::select(-common_name) |>
  dplyr::rename(
    Region = region,
    Year = year,
    Length = length,
    Age = age,
    Mass = mass
  ) |>
  gt(groupname_col = "Region") |>  
  gt::tab_header(
    title = "Biological samples by year and region"
  ) |>
  gt::fmt_number(
    columns = 3:5,
    decimals = 0, 
    sep_mark = ","
  )
   
```
